package me.xcoding.opencdc.binlog.event.management;

import me.xcoding.opencdc.binlog.EventContext;
import me.xcoding.opencdc.binlog.event.Event;
import me.xcoding.opencdc.binlog.parser.EventParser;
import me.xcoding.opencdc.mysql.protocol.BasicReader;

/**
 * <b> HeartBeat Event </b>
 * 
 * </br></br>
 * An artificial event generated by the master. It isn't written to the relay logs.
 * </br>
 * </br>
 * It is added by the master after the replication connection was idle for x-seconds 
 * to update the slave's Seconds_Behind_Master timestamp in the SHOW SLAVE STATUS 
 * output.
 * </br>
 * </br>
 * 
 * It has no payload nor post-header.
 * 
 * @author Teny Zh(zh.Teny.1@gmail.com)
 * @see http://dev.mysql.com/doc/internals/en/heartbeat-event.html
 */
public class HeartbeatLogEvent extends Event implements EventParser {

	@Override
	public Event parser(EventContext context, BasicReader reader) {
		return null;
	}
}
